// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package repos

import (
	"context"
	"database/sql"
	"fmt"
)

type DBTX interface {
	ExecContext(context.Context, string, ...interface{}) (sql.Result, error)
	PrepareContext(context.Context, string) (*sql.Stmt, error)
	QueryContext(context.Context, string, ...interface{}) (*sql.Rows, error)
	QueryRowContext(context.Context, string, ...interface{}) *sql.Row
}

func New(db DBTX) *Queries {
	return &Queries{db: db}
}

func Prepare(ctx context.Context, db DBTX) (*Queries, error) {
	q := Queries{db: db}
	var err error
	if q.addCategoryStmt, err = db.PrepareContext(ctx, addCategory); err != nil {
		return nil, fmt.Errorf("error preparing query AddCategory: %w", err)
	}
	if q.addImageStmt, err = db.PrepareContext(ctx, addImage); err != nil {
		return nil, fmt.Errorf("error preparing query AddImage: %w", err)
	}
	if q.addPostToCategoryStmt, err = db.PrepareContext(ctx, addPostToCategory); err != nil {
		return nil, fmt.Errorf("error preparing query AddPostToCategory: %w", err)
	}
	if q.addTagStmt, err = db.PrepareContext(ctx, addTag); err != nil {
		return nil, fmt.Errorf("error preparing query AddTag: %w", err)
	}
	if q.addTagToPostStmt, err = db.PrepareContext(ctx, addTagToPost); err != nil {
		return nil, fmt.Errorf("error preparing query AddTagToPost: %w", err)
	}
	if q.createPostStmt, err = db.PrepareContext(ctx, createPost); err != nil {
		return nil, fmt.Errorf("error preparing query CreatePost: %w", err)
	}
	if q.createUserStmt, err = db.PrepareContext(ctx, createUser); err != nil {
		return nil, fmt.Errorf("error preparing query CreateUser: %w", err)
	}
	if q.deleteCategoryStmt, err = db.PrepareContext(ctx, deleteCategory); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteCategory: %w", err)
	}
	if q.deleteImageStmt, err = db.PrepareContext(ctx, deleteImage); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteImage: %w", err)
	}
	if q.deletePostStmt, err = db.PrepareContext(ctx, deletePost); err != nil {
		return nil, fmt.Errorf("error preparing query DeletePost: %w", err)
	}
	if q.deleteTagStmt, err = db.PrepareContext(ctx, deleteTag); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteTag: %w", err)
	}
	if q.deleteUserStmt, err = db.PrepareContext(ctx, deleteUser); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteUser: %w", err)
	}
	if q.findPostsStmt, err = db.PrepareContext(ctx, findPosts); err != nil {
		return nil, fmt.Errorf("error preparing query FindPosts: %w", err)
	}
	if q.findUsersStmt, err = db.PrepareContext(ctx, findUsers); err != nil {
		return nil, fmt.Errorf("error preparing query FindUsers: %w", err)
	}
	if q.getAllCategoriesStmt, err = db.PrepareContext(ctx, getAllCategories); err != nil {
		return nil, fmt.Errorf("error preparing query GetAllCategories: %w", err)
	}
	if q.getAllImagesStmt, err = db.PrepareContext(ctx, getAllImages); err != nil {
		return nil, fmt.Errorf("error preparing query GetAllImages: %w", err)
	}
	if q.getAllPostsStmt, err = db.PrepareContext(ctx, getAllPosts); err != nil {
		return nil, fmt.Errorf("error preparing query GetAllPosts: %w", err)
	}
	if q.getAllTagsStmt, err = db.PrepareContext(ctx, getAllTags); err != nil {
		return nil, fmt.Errorf("error preparing query GetAllTags: %w", err)
	}
	if q.getAllUsersStmt, err = db.PrepareContext(ctx, getAllUsers); err != nil {
		return nil, fmt.Errorf("error preparing query GetAllUsers: %w", err)
	}
	if q.getCategoryByIDStmt, err = db.PrepareContext(ctx, getCategoryByID); err != nil {
		return nil, fmt.Errorf("error preparing query GetCategoryByID: %w", err)
	}
	if q.getChildCategoriesStmt, err = db.PrepareContext(ctx, getChildCategories); err != nil {
		return nil, fmt.Errorf("error preparing query GetChildCategories: %w", err)
	}
	if q.getImageByIDStmt, err = db.PrepareContext(ctx, getImageByID); err != nil {
		return nil, fmt.Errorf("error preparing query GetImageByID: %w", err)
	}
	if q.getPostsByCategoryIDStmt, err = db.PrepareContext(ctx, getPostsByCategoryID); err != nil {
		return nil, fmt.Errorf("error preparing query GetPostsByCategoryID: %w", err)
	}
	if q.getPostsByCategoryNameStmt, err = db.PrepareContext(ctx, getPostsByCategoryName); err != nil {
		return nil, fmt.Errorf("error preparing query GetPostsByCategoryName: %w", err)
	}
	if q.getPostsByStatusStmt, err = db.PrepareContext(ctx, getPostsByStatus); err != nil {
		return nil, fmt.Errorf("error preparing query GetPostsByStatus: %w", err)
	}
	if q.getPostsByTagIDStmt, err = db.PrepareContext(ctx, getPostsByTagID); err != nil {
		return nil, fmt.Errorf("error preparing query GetPostsByTagID: %w", err)
	}
	if q.getPostsByTagNameStmt, err = db.PrepareContext(ctx, getPostsByTagName); err != nil {
		return nil, fmt.Errorf("error preparing query GetPostsByTagName: %w", err)
	}
	if q.getPostsByUserIDStmt, err = db.PrepareContext(ctx, getPostsByUserID); err != nil {
		return nil, fmt.Errorf("error preparing query GetPostsByUserID: %w", err)
	}
	if q.getRootCategoriesStmt, err = db.PrepareContext(ctx, getRootCategories); err != nil {
		return nil, fmt.Errorf("error preparing query GetRootCategories: %w", err)
	}
	if q.getTagByIDStmt, err = db.PrepareContext(ctx, getTagByID); err != nil {
		return nil, fmt.Errorf("error preparing query GetTagByID: %w", err)
	}
	if q.getUncategorizedPostsStmt, err = db.PrepareContext(ctx, getUncategorizedPosts); err != nil {
		return nil, fmt.Errorf("error preparing query GetUncategorizedPosts: %w", err)
	}
	if q.getUserByIDStmt, err = db.PrepareContext(ctx, getUserByID); err != nil {
		return nil, fmt.Errorf("error preparing query GetUserByID: %w", err)
	}
	if q.updateCategoryStmt, err = db.PrepareContext(ctx, updateCategory); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateCategory: %w", err)
	}
	if q.updatePostBodyStmt, err = db.PrepareContext(ctx, updatePostBody); err != nil {
		return nil, fmt.Errorf("error preparing query UpdatePostBody: %w", err)
	}
	if q.updatePostMetadataStmt, err = db.PrepareContext(ctx, updatePostMetadata); err != nil {
		return nil, fmt.Errorf("error preparing query UpdatePostMetadata: %w", err)
	}
	if q.updatePostStatusStmt, err = db.PrepareContext(ctx, updatePostStatus); err != nil {
		return nil, fmt.Errorf("error preparing query UpdatePostStatus: %w", err)
	}
	if q.updateUserInfoStmt, err = db.PrepareContext(ctx, updateUserInfo); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateUserInfo: %w", err)
	}
	if q.updateUserPasswordStmt, err = db.PrepareContext(ctx, updateUserPassword); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateUserPassword: %w", err)
	}
	if q.updateUserRoleStmt, err = db.PrepareContext(ctx, updateUserRole); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateUserRole: %w", err)
	}
	return &q, nil
}

func (q *Queries) Close() error {
	var err error
	if q.addCategoryStmt != nil {
		if cerr := q.addCategoryStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing addCategoryStmt: %w", cerr)
		}
	}
	if q.addImageStmt != nil {
		if cerr := q.addImageStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing addImageStmt: %w", cerr)
		}
	}
	if q.addPostToCategoryStmt != nil {
		if cerr := q.addPostToCategoryStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing addPostToCategoryStmt: %w", cerr)
		}
	}
	if q.addTagStmt != nil {
		if cerr := q.addTagStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing addTagStmt: %w", cerr)
		}
	}
	if q.addTagToPostStmt != nil {
		if cerr := q.addTagToPostStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing addTagToPostStmt: %w", cerr)
		}
	}
	if q.createPostStmt != nil {
		if cerr := q.createPostStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createPostStmt: %w", cerr)
		}
	}
	if q.createUserStmt != nil {
		if cerr := q.createUserStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createUserStmt: %w", cerr)
		}
	}
	if q.deleteCategoryStmt != nil {
		if cerr := q.deleteCategoryStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteCategoryStmt: %w", cerr)
		}
	}
	if q.deleteImageStmt != nil {
		if cerr := q.deleteImageStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteImageStmt: %w", cerr)
		}
	}
	if q.deletePostStmt != nil {
		if cerr := q.deletePostStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deletePostStmt: %w", cerr)
		}
	}
	if q.deleteTagStmt != nil {
		if cerr := q.deleteTagStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteTagStmt: %w", cerr)
		}
	}
	if q.deleteUserStmt != nil {
		if cerr := q.deleteUserStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteUserStmt: %w", cerr)
		}
	}
	if q.findPostsStmt != nil {
		if cerr := q.findPostsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing findPostsStmt: %w", cerr)
		}
	}
	if q.findUsersStmt != nil {
		if cerr := q.findUsersStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing findUsersStmt: %w", cerr)
		}
	}
	if q.getAllCategoriesStmt != nil {
		if cerr := q.getAllCategoriesStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getAllCategoriesStmt: %w", cerr)
		}
	}
	if q.getAllImagesStmt != nil {
		if cerr := q.getAllImagesStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getAllImagesStmt: %w", cerr)
		}
	}
	if q.getAllPostsStmt != nil {
		if cerr := q.getAllPostsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getAllPostsStmt: %w", cerr)
		}
	}
	if q.getAllTagsStmt != nil {
		if cerr := q.getAllTagsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getAllTagsStmt: %w", cerr)
		}
	}
	if q.getAllUsersStmt != nil {
		if cerr := q.getAllUsersStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getAllUsersStmt: %w", cerr)
		}
	}
	if q.getCategoryByIDStmt != nil {
		if cerr := q.getCategoryByIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getCategoryByIDStmt: %w", cerr)
		}
	}
	if q.getChildCategoriesStmt != nil {
		if cerr := q.getChildCategoriesStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getChildCategoriesStmt: %w", cerr)
		}
	}
	if q.getImageByIDStmt != nil {
		if cerr := q.getImageByIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getImageByIDStmt: %w", cerr)
		}
	}
	if q.getPostsByCategoryIDStmt != nil {
		if cerr := q.getPostsByCategoryIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getPostsByCategoryIDStmt: %w", cerr)
		}
	}
	if q.getPostsByCategoryNameStmt != nil {
		if cerr := q.getPostsByCategoryNameStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getPostsByCategoryNameStmt: %w", cerr)
		}
	}
	if q.getPostsByStatusStmt != nil {
		if cerr := q.getPostsByStatusStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getPostsByStatusStmt: %w", cerr)
		}
	}
	if q.getPostsByTagIDStmt != nil {
		if cerr := q.getPostsByTagIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getPostsByTagIDStmt: %w", cerr)
		}
	}
	if q.getPostsByTagNameStmt != nil {
		if cerr := q.getPostsByTagNameStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getPostsByTagNameStmt: %w", cerr)
		}
	}
	if q.getPostsByUserIDStmt != nil {
		if cerr := q.getPostsByUserIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getPostsByUserIDStmt: %w", cerr)
		}
	}
	if q.getRootCategoriesStmt != nil {
		if cerr := q.getRootCategoriesStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getRootCategoriesStmt: %w", cerr)
		}
	}
	if q.getTagByIDStmt != nil {
		if cerr := q.getTagByIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getTagByIDStmt: %w", cerr)
		}
	}
	if q.getUncategorizedPostsStmt != nil {
		if cerr := q.getUncategorizedPostsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getUncategorizedPostsStmt: %w", cerr)
		}
	}
	if q.getUserByIDStmt != nil {
		if cerr := q.getUserByIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getUserByIDStmt: %w", cerr)
		}
	}
	if q.updateCategoryStmt != nil {
		if cerr := q.updateCategoryStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateCategoryStmt: %w", cerr)
		}
	}
	if q.updatePostBodyStmt != nil {
		if cerr := q.updatePostBodyStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updatePostBodyStmt: %w", cerr)
		}
	}
	if q.updatePostMetadataStmt != nil {
		if cerr := q.updatePostMetadataStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updatePostMetadataStmt: %w", cerr)
		}
	}
	if q.updatePostStatusStmt != nil {
		if cerr := q.updatePostStatusStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updatePostStatusStmt: %w", cerr)
		}
	}
	if q.updateUserInfoStmt != nil {
		if cerr := q.updateUserInfoStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateUserInfoStmt: %w", cerr)
		}
	}
	if q.updateUserPasswordStmt != nil {
		if cerr := q.updateUserPasswordStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateUserPasswordStmt: %w", cerr)
		}
	}
	if q.updateUserRoleStmt != nil {
		if cerr := q.updateUserRoleStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateUserRoleStmt: %w", cerr)
		}
	}
	return err
}

func (q *Queries) exec(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (sql.Result, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).ExecContext(ctx, args...)
	case stmt != nil:
		return stmt.ExecContext(ctx, args...)
	default:
		return q.db.ExecContext(ctx, query, args...)
	}
}

func (q *Queries) query(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (*sql.Rows, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryContext(ctx, args...)
	default:
		return q.db.QueryContext(ctx, query, args...)
	}
}

func (q *Queries) queryRow(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) *sql.Row {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryRowContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryRowContext(ctx, args...)
	default:
		return q.db.QueryRowContext(ctx, query, args...)
	}
}

type Queries struct {
	db                         DBTX
	tx                         *sql.Tx
	addCategoryStmt            *sql.Stmt
	addImageStmt               *sql.Stmt
	addPostToCategoryStmt      *sql.Stmt
	addTagStmt                 *sql.Stmt
	addTagToPostStmt           *sql.Stmt
	createPostStmt             *sql.Stmt
	createUserStmt             *sql.Stmt
	deleteCategoryStmt         *sql.Stmt
	deleteImageStmt            *sql.Stmt
	deletePostStmt             *sql.Stmt
	deleteTagStmt              *sql.Stmt
	deleteUserStmt             *sql.Stmt
	findPostsStmt              *sql.Stmt
	findUsersStmt              *sql.Stmt
	getAllCategoriesStmt       *sql.Stmt
	getAllImagesStmt           *sql.Stmt
	getAllPostsStmt            *sql.Stmt
	getAllTagsStmt             *sql.Stmt
	getAllUsersStmt            *sql.Stmt
	getCategoryByIDStmt        *sql.Stmt
	getChildCategoriesStmt     *sql.Stmt
	getImageByIDStmt           *sql.Stmt
	getPostsByCategoryIDStmt   *sql.Stmt
	getPostsByCategoryNameStmt *sql.Stmt
	getPostsByStatusStmt       *sql.Stmt
	getPostsByTagIDStmt        *sql.Stmt
	getPostsByTagNameStmt      *sql.Stmt
	getPostsByUserIDStmt       *sql.Stmt
	getRootCategoriesStmt      *sql.Stmt
	getTagByIDStmt             *sql.Stmt
	getUncategorizedPostsStmt  *sql.Stmt
	getUserByIDStmt            *sql.Stmt
	updateCategoryStmt         *sql.Stmt
	updatePostBodyStmt         *sql.Stmt
	updatePostMetadataStmt     *sql.Stmt
	updatePostStatusStmt       *sql.Stmt
	updateUserInfoStmt         *sql.Stmt
	updateUserPasswordStmt     *sql.Stmt
	updateUserRoleStmt         *sql.Stmt
}

func (q *Queries) WithTx(tx *sql.Tx) *Queries {
	return &Queries{
		db:                         tx,
		tx:                         tx,
		addCategoryStmt:            q.addCategoryStmt,
		addImageStmt:               q.addImageStmt,
		addPostToCategoryStmt:      q.addPostToCategoryStmt,
		addTagStmt:                 q.addTagStmt,
		addTagToPostStmt:           q.addTagToPostStmt,
		createPostStmt:             q.createPostStmt,
		createUserStmt:             q.createUserStmt,
		deleteCategoryStmt:         q.deleteCategoryStmt,
		deleteImageStmt:            q.deleteImageStmt,
		deletePostStmt:             q.deletePostStmt,
		deleteTagStmt:              q.deleteTagStmt,
		deleteUserStmt:             q.deleteUserStmt,
		findPostsStmt:              q.findPostsStmt,
		findUsersStmt:              q.findUsersStmt,
		getAllCategoriesStmt:       q.getAllCategoriesStmt,
		getAllImagesStmt:           q.getAllImagesStmt,
		getAllPostsStmt:            q.getAllPostsStmt,
		getAllTagsStmt:             q.getAllTagsStmt,
		getAllUsersStmt:            q.getAllUsersStmt,
		getCategoryByIDStmt:        q.getCategoryByIDStmt,
		getChildCategoriesStmt:     q.getChildCategoriesStmt,
		getImageByIDStmt:           q.getImageByIDStmt,
		getPostsByCategoryIDStmt:   q.getPostsByCategoryIDStmt,
		getPostsByCategoryNameStmt: q.getPostsByCategoryNameStmt,
		getPostsByStatusStmt:       q.getPostsByStatusStmt,
		getPostsByTagIDStmt:        q.getPostsByTagIDStmt,
		getPostsByTagNameStmt:      q.getPostsByTagNameStmt,
		getPostsByUserIDStmt:       q.getPostsByUserIDStmt,
		getRootCategoriesStmt:      q.getRootCategoriesStmt,
		getTagByIDStmt:             q.getTagByIDStmt,
		getUncategorizedPostsStmt:  q.getUncategorizedPostsStmt,
		getUserByIDStmt:            q.getUserByIDStmt,
		updateCategoryStmt:         q.updateCategoryStmt,
		updatePostBodyStmt:         q.updatePostBodyStmt,
		updatePostMetadataStmt:     q.updatePostMetadataStmt,
		updatePostStatusStmt:       q.updatePostStatusStmt,
		updateUserInfoStmt:         q.updateUserInfoStmt,
		updateUserPasswordStmt:     q.updateUserPasswordStmt,
		updateUserRoleStmt:         q.updateUserRoleStmt,
	}
}
